skeleton for dataloader, needs linked in cmake for all my cpp files
tpool2/slamdunk pull request #3
Opened 2021-12-02 04:48 UTC by csmaster23

2021-12-03 01:19 UTC, tpool2 commented on include/load_data.hpp
> +// #include "opencv2/opencv.hpp"
Can you remove these lines?

2021-12-03 01:25 UTC, tpool2 reviewed
See comments

2021-12-03 01:25 UTC, tpool2 commented on src/slamdunk.cpp
> +    // probably want a better place to put these but for now
What are your thoughts about creating a .json file for this stuff?

2021-12-03 01:25 UTC, tpool2 commented on include/load_data.hpp
> +  std::vector<cv::Mat> mat_images;
Could we get a more descriptive variable name here?

2021-12-04 05:31 UTC, csmaster23 commented
New pull request

2021-12-04 05:45 UTC, tpool2 requested changes
Reviewed

2021-12-04 05:45 UTC, tpool2 commented on include/load_data.hpp
> +  std::vector<std::vector<cv::KeyPoint>> feature_vec;
Can you explain a little more about what's going on here?

2021-12-04 05:45 UTC, tpool2 commented on include/load_data.hpp
> +  void save_image_with_features(cv::Mat image_in, std::vector<cv::KeyPoint> key_points, std::string save_path);
Can you please add documentation for each of these functions? i.e. purpose, inputs, outputs, etc

2021-12-04 05:45 UTC, tpool2 commented on src/load_data.cpp
> +        // --- Delete this after our two images test ---
Mark this as TODO

2021-12-04 05:45 UTC, tpool2 commented on src/load_data.cpp
> +        const cv::Mat image = cv::imread(entry.path(), 0); //Load as grayscale
Can you put all comments on top of the code? Just for consistency's sake

2021-12-04 05:45 UTC, tpool2 commented on src/load_data.cpp
> +        if (plot)
Can you put all of this plotting logic in a separate function? Ideally we should try to keep functions no more than 20 lines or so

2021-12-04 06:06 UTC, tpool2 requested changes

2021-12-04 06:06 UTC, tpool2 commented on include/load_data.hpp
>    std::string dataset_name;
If we have getters and setters for these fields, then these should be private and not public.

2021-12-04 06:22 UTC, tpool2 approved these changes

2021-12-04 06:23 UTC, tpool2 commented
Nice work

2021-12-04 06:23 UTC, merged